### ISSUE TITLE
Crash when turning device in "Favourite canteens" dialogue

### ISSUE THREAD

**Issue by cyroxx** [domoritz/open-mensa-android#27]
The app crashes when you try to edit your favourite canteens and turn your device.

Steps to reproduce:
1. Open APP
2. Open preferences dialogue
3. tap on 'Favourite Canteens'
4. Change the orientation of your device -> 'Unfortunately, OpenMensa has stopped'

```
01-30 01:38:43.638  24162-24162/de.uni_potsdam.hpi.openmensa D/AndroidRuntime﹕ Shutting down VM
01-30 01:38:43.638  24162-24162/de.uni_potsdam.hpi.openmensa W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41730d40)
01-30 01:38:43.679  24162-24162/de.uni_potsdam.hpi.openmensa E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: de.uni_potsdam.hpi.openmensa, PID: 24162
    java.lang.RuntimeException: Unable to start activity ComponentInfo{de.uni_potsdam.hpi.openmensa/de.uni_potsdam.hpi.openmensa.api.preferences.SettingsActivity}: android.view.InflateException: Binary XML file line #6: Error inflating class java.lang.reflect.Constructor
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2198)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3805)
            at android.app.ActivityThread.access$900(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1216)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5097)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class java.lang.reflect.Constructor
            at android.preference.GenericInflater.createItem(GenericInflater.java:397)
            at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:430)
            at android.preference.GenericInflater.rInflate(GenericInflater.java:481)
            at android.preference.GenericInflater.rInflate(GenericInflater.java:493)
            at android.preference.GenericInflater.inflate(GenericInflater.java:326)
            at android.preference.GenericInflater.inflate(GenericInflater.java:263)
            at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:272)
            at android.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:285)
            at de.uni_potsdam.hpi.openmensa.api.preferences.SettingsFragment.onCreate(SettingsFragment.java:28)
            at android.app.Fragment.performCreate(Fragment.java:1678)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:859)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1044)
            at android.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:1850)
            at android.app.Activity.onCreate(Activity.java:910)
            at android.preference.PreferenceActivity.onCreate(PreferenceActivity.java:514)
            at de.uni_potsdam.hpi.openmensa.api.preferences.SettingsActivity.onCreate(SettingsActivity.java:28)
            at android.app.Activity.performCreate(Activity.java:5248)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3805)
            at android.app.ActivityThread.access$900(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1216)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5097)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at android.preference.GenericInflater.createItem(GenericInflater.java:383)
            at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:430)
            at android.preference.GenericInflater.rInflate(GenericInflater.java:481)
            at android.preference.GenericInflater.rInflate(GenericInflater.java:493)
            at android.preference.GenericInflater.inflate(GenericInflater.java:326)
            at android.preference.GenericInflater.inflate(GenericInflater.java:263)
            at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:272)
            at android.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:285)
            at de.uni_potsdam.hpi.openmensa.api.preferences.SettingsFragment.onCreate(SettingsFragment.java:28)
            at android.app.Fragment.performCreate(Fragment.java:1678)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:859)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1044)
            at android.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:1850)
            at android.app.Activity.onCreate(Activity.java:910)
            at android.preference.PreferenceActivity.onCreate(PreferenceActivity.java:514)
            at de.uni_potsdam.hpi.openmensa.api.preferences.SettingsActivity.onCreate(SettingsActivity.java:28)
            at android.app.Activity.performCreate(Activity.java:5248)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3805)
            at android.app.ActivityThread.access$900(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1216)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5097)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at android.preference.MultiSelectListPreference.onGetDefaultValue(MultiSelectListPreference.java:212)
            at android.preference.Preference.<init>(Preference.java:268)
            at android.preference.DialogPreference.<init>(DialogPreference.java:69)
            at android.preference.DialogPreference.<init>(DialogPreference.java:90)
            at android.preference.MultiSelectListPreference.<init>(MultiSelectListPreference.java:49)
            at de.uni_potsdam.hpi.openmensa.api.preferences.SelectFavouritesPreference.<init>(SelectFavouritesPreference.java:43)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at android.preference.GenericInflater.createItem(GenericInflater.java:383)
            at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:430)
            at android.preference.GenericInflater.rInflate(GenericInflater.java:481)
            at android.preference.GenericInflater.rInflate(GenericInflater.java:493)
            at android.preference.GenericInflater.inflate(GenericInflater.java:326)
            at android.preference.GenericInflater.inflate(GenericInflater.java:263)
            at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:272)
            at android.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:285)
            at de.uni_potsdam.hpi.openmensa.api.preferences.SettingsFragment.onCreate(SettingsFragment.java:28)
            at android.app.Fragment.performCreate(Fragment.java:1678)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:859)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1044)
            at android.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:1850)
            at android.app.Activity.onCreate(Activity.java:910)
            at android.preference.PreferenceActivity.onCreate(PreferenceActivity.java:514)
            at de.uni_potsdam.hpi.openmensa.api.preferences.SettingsActivity.onCreate(SettingsActivity.java:28)
            at android.app.Activity.performCreate(Activity.java:5248)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3805)
            at android.app.ActivityThread.access$900(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1216)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5097)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by cyroxx** [comment]
Could you shed some light on your motivation for closing this issue? You might possibly think this is a duplicate of #25, but it is not.

**Comment by domoritz** [comment]
Sorry. Didn't mean to close.

**Comment by l-jonas** [comment]
Fixed by https://github.com/domoritz/open-mensa-android/commit/4b91a256581d52cb1994b74d83c575baca962d05
